/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/kane-clover.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function KaneClover(props) {
  const { nodes, materials } = useGLTF("/kane-clover.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Text.geometry} material={nodes.Text.material} />
    </group>
  );
}

useGLTF.preload("/kane-clover.glb");
